## Set the base image
FROM 192.168.149.132/colinrepo/centos7:v1.1
## File authoer / Maintianer
MAINTAINER Colin <szl_colin@163.com>
## Install necessary tools
# yum install gcc autoconf -y
RUN yum install -y perl perl-devel libaio-devel numactl.x86_64 \
#   automake make cmake ncurses-devel \
    net-tools wget && \
    yum clean all && \
    rm -rf /var/cache/yum/* && \
## Add necessary user&group
    groupadd -f mysql && useradd mysql -g mysql -M -s /sbin/nologin
#    mkdir -p /data/mysql/data && touch /data/mysql/mysql_3306.err 
COPY my.cnf /etc/my.cnf
COPY mysql_init.sh /root/mysql_init.sh

## Install nginx
#ENV MYSQL_VERSION 5.6.59
#RUN wget http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.29.tar.gz && \
#    tar zxf mysql-5.6.29.tar.gz -C /usr/src && \
#    cd /usr/src/mysql-5.6.29 && \
#    cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/mysql \
#    -DMYSQL_DATADIR=/data/mysql/data \
#    -DSYSCONFDIR=/etc \
#    -DMYSQL_TCP_PORT=3306 \ 
#    -DMYSQL_UNIX_ADDR=/var/lib/mysql/mysql.sock \
#    -DWITH_INNOBASE_STORAGE_ENGINE=1 \
#    -DWITH_MYISAM_STORAGE_ENGINE=1 \
#    -DENABLED_LOCAL_INFILE=1 \
#    -DWITH_PARTITION_STORAGE_ENGINE=1 \
#    -DDEFAULT_CHARSET=utf8 \
#    -DEXTRA_CHARSETS=all \
#    -DDEFAULT_COLLATION=utf8_general_ci \
#    -DWITH-MYSQLD-LDFLAGS=-all-static \
#    -DWITH-CLIENT-LD-FLAGS=-all-static \
#    -DWITH_DEBUG=0 && \
#    make -j 4 && make install && \
#COPY mysql-5.6.43-linux-glibc2.12-x86_64.tar.gz / 
WORKDIR /usr/src
RUN wget https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.43-linux-glibc2.12-x86_64.tar.gz && \
    tar zxf mysql-5.6.43-linux-glibc2.12-x86_64.tar.gz && \
    mv -f mysql-5.6.43-linux-glibc2.12-x86_64 /usr/local/mysql && \
    rm -rf mysql-5.6.43-linux-glibc2.12-x86_64* && \
    chown -R mysql:mysql /usr/local/mysql && \
    ln -s /usr/local/mysql/scripts/mysql_install_db /usr/local/mysql/bin/mysql_install_db && \
    chmod +x /root/mysql_init.sh && \
#    chown -R mysql:mysql /data/mysql && \

#############################################################################################################
#    CAUTION: Because hostname will be changed when a new container created and once hostname changed,
#    need to initialize mysql data file, so need to run mysql_install_db in CMD part when creating container.
#############################################################################################################
#    /usr/local/mysql/scripts/mysql_install_db \ 
#    --basedir=/usr/local/mysql \
#    --datadir=/data/mysql/data \
#    --user=mysql && \

    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

## Set ENV path and copy configuration file from local
ENV PATH $PATH:/usr/local/mysql/bin
#COPY mysqld /etc/init.d/mysqld
#RUN chmod +x /etc/init.d/mysqld && /etc/init.d/mysqld start
WORKDIR /usr/local/mysql

## Expose ports
EXPOSE 3306
## Set the default command to execute when creating a new container
ENTRYPOINT ["/root/mysql_init.sh"]
#CMD ["mysqld_safe","--defaults-file=/etc/my.cnf","--user=mysql"]
