---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-wp-deploy
  namespace: php-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php 
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME 
      containers:
      - name: tomcat 
        image: $IMAGE_NAME 
        ports:
        - containerPort: 8080
          name: ng-port
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12


---
apiVersion: v1
kind: Service
metadata:
  name: ng-php-wp
  namespace: php-test
spec:
  selector:
    app: nginx-php 
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-php-wp-ing
  namespace: php-test
  annotations:
     kubernetes.io/ingress.class: "ng-php"  
spec:
  rules:
  - host: wp.colin.org
    http:
      paths:
      - path: /
        backend:
          serviceName: ng-php-wp 
          servicePort: 8001

