## Set the base image
#FROM centos:7
FROM 192.168.149.132/colinrepo/centos7:v1.1
## File authoer / Maintianer
MAINTAINER ColinShih <szl_colin@163.com>
## Install necessary tools
RUN yum install -y make \
#gcc gcc-c++ make \
    openssl-devel pcre-devel gd-devel \
    iproute net-tools telnet wget curl && \
    yum clean all && \
    rm -rf /var/cache/yum/*
## Add necessary user&group
RUN groupadd -f www && useradd -g www www -M -s /sbin/nologin

## Install nginx
ENV NGINX_VERSION 1.15.5
RUN wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz && \
    tar zxf nginx-$NGINX_VERSION.tar.gz && \
    echo "Installing nginx..." && \
    cd nginx-$NGINX_VERSION &&\
    ./configure --prefix=/usr/local/nginx \
    --user=www \
    --group=www \
    --with-http_ssl_module \
    --with-http_flv_module \
    --with-http_stub_status_module \
    --with-http_gzip_static_module \
    --with-pcre > /dev/null && \
    make -j 4 >/dev/null && make install > /dev/null && \
    cd / && rm -rf nginx-$NGINX_VERSION && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

## Set ENV path and copy configuration file from local
ENV PATH $PATH:/usr/local/nginx/sbin
COPY nginx.conf /usr/local/nginx/conf/nginx.conf
WORKDIR /usr/local/nginx

## Expose ports
EXPOSE 80
## Set the default command to execute when creating a new container
CMD ["nginx", "-g", "daemon off;"]
